## Spring properties
# Service Registers under this name
spring:
  application:
    name: accounts-microservice
    
# Discovery Server Access
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:2345/eureka/
    
# HTTP Server (Tomcat) port
server:
  port: 2346